# Generated by Django 4.2.7 on 2025-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='class_teacher_signature_required',
            field=models.BooleanField(default=False, help_text='Require class teacher signature on report cards'),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_scale_a_min',
            field=models.IntegerField(default=80, help_text='Minimum score for grade A'),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_scale_b_min',
            field=models.IntegerField(default=70, help_text='Minimum score for grade B'),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_scale_c_min',
            field=models.IntegerField(default=60, help_text='Minimum score for grade C'),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_scale_d_min',
            field=models.IntegerField(default=50, help_text='Minimum score for grade D'),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_scale_f_min',
            field=models.IntegerField(default=0, help_text='Minimum score for grade F'),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_signature',
            field=models.FileField(blank=True, help_text='Principal signature image for report cards', null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='school',
            name='report_footer_text',
            field=models.TextField(blank=True, help_text='Custom footer text for report cards (e.g., next term info)'),
        ),
        migrations.AddField(
            model_name='school',
            name='report_header_text',
            field=models.TextField(blank=True, help_text='Custom header text for report cards (e.g., school vision/mission)'),
        ),
        migrations.AddField(
            model_name='school',
            name='report_template',
            field=models.CharField(choices=[('STANDARD', 'Standard Template'), ('DETAILED', 'Detailed Template with Comments'), ('COMPACT', 'Compact Template'), ('CUSTOM', 'Custom Template')], default='STANDARD', help_text='Report card template style', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='score_entry_mode',
            field=models.CharField(choices=[('CLASS_TEACHER', 'Class Teacher Mode - Class teachers enter all subjects'), ('SUBJECT_TEACHER', 'Subject Teacher Mode - Subject teachers enter their own scores')], default='CLASS_TEACHER', help_text='Determines whether class teachers or subject teachers enter scores', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='show_attendance',
            field=models.BooleanField(default=True, help_text='Include attendance information on report cards'),
        ),
        migrations.AddField(
            model_name='school',
            name='show_behavior_comments',
            field=models.BooleanField(default=True, help_text='Include behavior/conduct comments'),
        ),
        migrations.AddField(
            model_name='school',
            name='show_class_average',
            field=models.BooleanField(default=True, help_text='Show class average on report cards'),
        ),
        migrations.AddField(
            model_name='school',
            name='show_position_in_class',
            field=models.BooleanField(default=True, help_text='Show student position in class ranking'),
        ),
    ]
