# Generated by Django 4.2.7 on 2025-11-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_class_teacher_signature_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_academic_year',
            field=models.CharField(blank=True, help_text='Current academic year (e.g., 2024/2025)', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='show_headteacher_signature',
            field=models.BooleanField(default=True, help_text='Show headteacher signature section on report cards'),
        ),
        migrations.AddField(
            model_name='school',
            name='show_student_photos',
            field=models.BooleanField(default=True, help_text='Show student photos on report cards'),
        ),
    ]
