# Generated by Django 4.2.7 on 2025-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_current_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='report_template',
            field=models.CharField(choices=[('STANDARD', 'Standard Template'), ('DETAILED', 'Detailed Template with Comments'), ('COMPACT', 'Compact Template'), ('GHANA_EDUCATION_SERVICE', 'Ghana Education Service Template'), ('CUSTOM', 'Custom Template')], default='STANDARD', help_text='Report card template style', max_length=30),
        ),
    ]
